// Mocks generated by Mockito 5.4.6 from annotations
// in well_task_app/test/providers/task_list_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:well_task_app/core/errors/failure.dart' as _i5;
import 'package:well_task_app/core/usecase/usecase.dart' as _i7;
import 'package:well_task_app/domain/entities/task.dart' as _i6;
import 'package:well_task_app/domain/usecases/tasks/add_task_usecase.dart'
    as _i9;
import 'package:well_task_app/domain/usecases/tasks/edit_task_usecase.dart'
    as _i10;
import 'package:well_task_app/domain/usecases/tasks/get_tasks_usecase.dart'
    as _i2;
import 'package:well_task_app/domain/usecases/tasks/remove_task_usecase.dart'
    as _i11;
import 'package:well_task_app/domain/usecases/tasks/toggle_alarm_usecase.dart'
    as _i13;
import 'package:well_task_app/domain/usecases/tasks/toggle_complete_usecase.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetTasksUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTasksUsecase extends _i1.Mock implements _i2.GetTasksUsecase {
  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Task>>> call(
    _i7.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.Task>>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, List<_i6.Task>>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.Task>>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, List<_i6.Task>>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Task>>>);
}

/// A class which mocks [AddTaskUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTaskUsecase extends _i1.Mock implements _i9.AddTaskUsecase {
  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(_i6.Task? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [EditTaskUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditTaskUsecase extends _i1.Mock implements _i10.EditTaskUsecase {
  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(_i10.EditTaskParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [RemoveTaskUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveTaskUsecase extends _i1.Mock implements _i11.RemoveTaskUsecase {
  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(String? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [ToggleCompleteUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleCompleteUsecase extends _i1.Mock
    implements _i12.ToggleCompleteUsecase {
  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(String? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [ToggleAlarmUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleAlarmUsecase extends _i1.Mock
    implements _i13.ToggleAlarmUsecase {
  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(String? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

